defaults:
  model_type: "2level"
  n_chains: 4
  n_samples: 2000
  n_warmup: 1000
  adapt_delta: 0.90
  max_treedepth: 12

runs:
  - name: "scpw_basic_single_session"
    perceptual_model: "scpw"
    response_model: "basic"
    hierarchy: "single_session"
    n_samples: 1000
  
  - name: "scpw_brt_single_session"
    perceptual_model: "scpw"
    response_model: "brt"
    hierarchy: "single_session"
    n_samples: 1000

  - name: "scpw_brrt_single_session"
    perceptual_model: "scpw"
    response_model: "brrt"
    hierarchy: "single_session"
    n_samples: 1000

  - name: "scpw_basic_single_subject"
    perceptual_model: "scpw"
    response_model: "basic"
    hierarchy: "single_subject"
    adapt_delta: 0.95
  
  - name: "scpw_brt_single_subject"
    perceptual_model: "scpw"
    response_model: "brt"
    hierarchy: "single_subject"
    adapt_delta: 0.95

  - name: "scpw_brrt_single_subject"
    perceptual_model: "scpw"
    response_model: "brrt"
    hierarchy: "single_subject"
    adapt_delta: 0.95

  - name: "scpw_basic_full"
    perceptual_model: "scpw"
    response_model: "basic"
    hierarchy: "full"
    adapt_delta: 0.95
    max_treedepth: 13
    n_warmup: 1500
  
  - name: "scpw_brt_full"
    perceptual_model: "scpw"
    response_model: "brt"
    hierarchy: "full"
    adapt_delta: 0.95
    max_treedepth: 13
    n_warmup: 1500

  - name: "scpw_brrt_full"
    perceptual_model: "scpw"
    response_model: "brrt"
    hierarchy: "full"
    adapt_delta: 0.95
    max_treedepth: 13
    n_warmup: 1500